import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

void main() {
  test('local evidence manifest is generated by the no-device gate', () {
    final verifyApp = File('../tools/verify-app.ps1').readAsStringSync();
    final manifestScript = File(
      '../tools/write-local-evidence-manifest.ps1',
    ).readAsStringSync();

    expect(verifyApp, contains('[switch]\$EvidenceManifest'));
    expect(verifyApp, contains('write-local-evidence-manifest.ps1'));
    expect(verifyApp, contains('\$EvidenceManifest = \$true'));
    expect(verifyApp, contains('local evidence manifest'));

    expect(manifestScript, contains('noDeviceEvidence'));
    expect(manifestScript, contains('forbiddenDeviceTargets'));
    expect(manifestScript, contains('verify-app.ps1 -AllLocal'));
    expect(manifestScript, contains('webVisualQaPng'));
    expect(manifestScript, contains('modelsim-transcript.log'));
    expect(manifestScript, contains('final-rgb-controller.map.rpt'));
    expect(manifestScript, contains('app-release.apk'));
    expect(manifestScript, contains('Get-FileHash'));
    expect(manifestScript, contains('manifest.json'));
    expect(manifestScript, contains('manifest.md'));
  });
}
